### ISSUE TITLE
Commit command using "git add ."

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/git-work#19]
The issue #8 has introduced a `git add .` command in the execution of `git work commit` command.
I believe this is not always good. Sometimes we need to commit just some files, not all that were changed.

@fabriciofx what will you think if we change `commit` command, introducing a new parameter like this?

`git work commit -a "message"`

This is could be related with #18 too.

**Comment by nunopicado** [comment]
I'd say this kind of thing is a stopper for me.
I sometimes create a few changes as part of my though process, and then commit my changes in different commits, picking which change belongs where. Having to commit all changes in one single commit is for me a no game.
But unfortunately I don't see a way of doing this kind of workflow via command line without loosing efficiency.

**Comment by mdbs99** [comment]
@nunopicado I agree with you. We need to commit always a few changes per command. Because this I consider this issue a bug and should be resolved.

>But unfortunately I don't see a way of doing this kind of workflow via command line without loosing efficiency.

The problem is adding files typing one by one. If you made many changes in many files may be a hard work to do the job using command line. In that case you can use `git gui` or we can think in something better...

**Comment by nunopicado** [comment]
I go to an extend in which I commit not this or that file, but this or that line in a changed file.
Sometimes the same file has changes which belong in different commits.

**Comment by mdbs99** [comment]
In these cases, using command line, we need to use `git add -p` to decide which lines need to be committed.

**Comment by nunopicado** [comment]
Or a GUI! :)

**Comment by mdbs99** [comment]
Yeah, of course. In fact I still use `git gui` and `gitk` together with the command line.
This project won't try to substitute a GUI. The major goal here is simplicity, effectiveness, and give to the users a flow to work.

**Comment by mdbs99** [comment]
Done in https://github.com/mdbs99/git-work/commit/7f825f15e4bdafd1fd5c4daf210f1d6eb29178ac.
