### ISSUE TITLE
Add install

### ISSUE THREAD

**Issue by fabriciofx** [mdbs99/git-work#6]
Let's create an easy way to install `git-work`. For example, `$ git-work.sh install`. I'll handle it.

**Comment by mdbs99** [comment]
I didn't get it. 
IMHO the easiest way to install is add an alias.
Could you explain more why is this important?

**Comment by mdbs99** [comment]
Now I understood.
Please, could you update [README:Installing](https://github.com/mdbs99/git-work/blob/master/README.md) section in this same PR?

And *Installation* may be a better section name.

**Comment by fabriciofx** [comment]
@mdbs99 I think it's important because it's an easier way to install it than execute the git alias command. Besides, I'm using this example to explain to my students how to contribute to an open source project. Say hello to my class! :)

**Comment by mdbs99** [comment]
WOW! That is nice. 
Hello class!

**Comment by mdbs99** [comment]
@fabriciofx it was merged in https://github.com/mdbs99/git-work/commit/f45b6bedfab07f889c955b2b85cef3ac927812b2 please, close.

**Comment by fabriciofx** [comment]
Closed #7.
