### ISSUE TITLE
Concatenate issue ID in comments

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/git-work#8]
Let's make a little change in `commit` command.
I would like to concatenate issue ID in each comment following this pattern: `#id: message`

We don't need to remember the issue ID for each comments.

**Comment by mdbs99** [comment]
@fabriciofx wdyt?

**Comment by fabriciofx** [comment]
@mdbs99 I think it a great idea! 😄

**Comment by mdbs99** [comment]
@fabriciofx but first we could check if the branch name is a number? Because if it is not, we won't use this pattern. What do you think?

**Comment by fabriciofx** [comment]
@mdbs99 It's a good idea. I can handle it. WDYT?

**Comment by mdbs99** [comment]
@fabriciofx go ahead!
